version: '3'
services:
  client:
    container_name: react-test-client
    ports:
      - "8080:8080"
    build:
      context: ./client
      dockerfile: Dockerfile

  server:
    container_name: node-test-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - postgres

  postgres:

    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
